// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $$0 from "./islands/AddCombinador.tsx";
import * as $$1 from "./islands/AddToCartButton/vnda.tsx";
import * as $$2 from "./islands/AddToCartButton/vtex.tsx";
import * as $$3 from "./islands/BenefitItem.tsx";
import * as $$4 from "./islands/CategoryBannersSlider.tsx";
import * as $$5 from "./islands/CategoryTextFooter.tsx";
import * as $$6 from "./islands/CategoryTextHeader.tsx";
import * as $$7 from "./islands/ColorsSimilars.tsx";
import * as $$8 from "./islands/Combination.tsx";
import * as $$9 from "./islands/CombinationItem.tsx";
import * as $$10 from "./islands/CombinationList.tsx";
import * as $$11 from "./islands/Conservation.tsx";
import * as $$12 from "./islands/Form.tsx";
import * as $$13 from "./islands/Header/Alert.tsx";
import * as $$14 from "./islands/Header/Buttons.tsx";
import * as $$15 from "./islands/Header/Cart/vnda.tsx";
import * as $$16 from "./islands/Header/Cart/vtex.tsx";
import * as $$17 from "./islands/Header/Drawers.tsx";
import * as $$18 from "./islands/Header/Searchbar.tsx";
import * as $$19 from "./islands/LojaItem.tsx";
import * as $$20 from "./islands/MeterHelp.tsx";
import * as $$21 from "./islands/Navbar.tsx";
import * as $$22 from "./islands/Newsletter.tsx";
import * as $$23 from "./islands/OutOfStock.tsx";
import * as $$24 from "./islands/PaginationCustom.tsx";
import * as $$25 from "./islands/Payments.tsx";
import * as $$26 from "./islands/Price.tsx";
import * as $$27 from "./islands/ProductImageZoom.tsx";
import * as $$28 from "./islands/SearchControls.tsx";
import * as $$29 from "./islands/ShippingSimulation.tsx";
import * as $$30 from "./islands/SliderJS.tsx";
import * as $$31 from "./islands/TabelaDeMedidas.tsx";
import * as $$32 from "./islands/WishlistButton.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
  },
  islands: {
    "./islands/AddCombinador.tsx": $$0,
    "./islands/AddToCartButton/vnda.tsx": $$1,
    "./islands/AddToCartButton/vtex.tsx": $$2,
    "./islands/BenefitItem.tsx": $$3,
    "./islands/CategoryBannersSlider.tsx": $$4,
    "./islands/CategoryTextFooter.tsx": $$5,
    "./islands/CategoryTextHeader.tsx": $$6,
    "./islands/ColorsSimilars.tsx": $$7,
    "./islands/Combination.tsx": $$8,
    "./islands/CombinationItem.tsx": $$9,
    "./islands/CombinationList.tsx": $$10,
    "./islands/Conservation.tsx": $$11,
    "./islands/Form.tsx": $$12,
    "./islands/Header/Alert.tsx": $$13,
    "./islands/Header/Buttons.tsx": $$14,
    "./islands/Header/Cart/vnda.tsx": $$15,
    "./islands/Header/Cart/vtex.tsx": $$16,
    "./islands/Header/Drawers.tsx": $$17,
    "./islands/Header/Searchbar.tsx": $$18,
    "./islands/LojaItem.tsx": $$19,
    "./islands/MeterHelp.tsx": $$20,
    "./islands/Navbar.tsx": $$21,
    "./islands/Newsletter.tsx": $$22,
    "./islands/OutOfStock.tsx": $$23,
    "./islands/PaginationCustom.tsx": $$24,
    "./islands/Payments.tsx": $$25,
    "./islands/Price.tsx": $$26,
    "./islands/ProductImageZoom.tsx": $$27,
    "./islands/SearchControls.tsx": $$28,
    "./islands/ShippingSimulation.tsx": $$29,
    "./islands/SliderJS.tsx": $$30,
    "./islands/TabelaDeMedidas.tsx": $$31,
    "./islands/WishlistButton.tsx": $$32,
  },
  baseUrl: import.meta.url,
};

export default manifest;
